---
title: "2_Part2beeped Preprocessing"
author: "WGD"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
#Load required packages
library(here)
library(dplyr)
library(lubridate)
library(readr)
library(janitor)
library(tidyr)

#Define path to EMA Part 2 data
part2_path <- here("data", "DVAL_EMA_Part2_beeped.csv")
```

```{r}
#Import data and define missing values for EMA variables to be used study analyses
# Define subset of participants
subset_ids <- c(
  102, 104, 107, 112, 113, 115, 116, 124, 125, 126, 127, 128, 133, 141, 
  150, 151, 154, 159, 163, 164, 166, 169, 175, 177, 180, 186, 188, 192, 
  195, 196, 197, 198, 199, 202, 206, 209, 210, 213, 214, 216, 218, 221, 
  222, 223, 233, 238, 240, 246, 252, 257, 262, 268, 273, 274, 278, 281, 
  282, 286, 287, 290, 291, 295, 297, 300, 301, 304, 310, 314, 320, 321, 
  329, 332, 340, 341, 342, 344, 346, 349, 351, 356, 362, 363, 369, 370, 
  372, 381, 383, 393, 394, 399, 416, 423, 427, 428, 430
)

# Then run your read_csv + cleaning pipeline
part2beeped <- read_csv(
  part2_path,
  na = c("-99", "__NA__", "NA", ""),
  col_types = cols(.default = col_character()),
  col_select = c(
    mood,
    smoke,
    before_survey,
    unpleasant,
    prior_mood,
    smoked_since_last_survey,
    pleasant,
    participant_id,
    session_id,
    completion_time,
    init_time
  )
) %>%
  filter(as.numeric(participant_id) %in% subset_ids) %>%
  mutate(
    smoked_since_last_survey = ifelse(
      smoked_since_last_survey == "opted out", "999", #Modification
      ifelse(smoked_since_last_survey == "6+", "6", smoked_since_last_survey) #Modification
    ),
    mood = ifelse(mood == "opted out", "999", mood),
    smoke = ifelse(smoke == "opted out", "999", smoke),
    before_survey = ifelse(before_survey == "opted out", "999", before_survey),
    unpleasant = ifelse(unpleasant == "opted out", "999", unpleasant),
    pleasant = ifelse(pleasant == "opted out", "999", pleasant),
    prior_mood = ifelse(prior_mood == "opted out", "999", prior_mood),
    participant_id = ifelse(participant_id == "opted out", "999", participant_id),
    session_id = ifelse(session_id == "opted out", "999", session_id)
  ) %>%
  mutate(
    smoked_since_last_survey = as.numeric(smoked_since_last_survey), #Modification
    prior_mood = as.numeric(prior_mood),
    mood = as.numeric(mood),
    smoke = as.numeric(smoke),
    unpleasant = as.numeric(unpleasant),
    pleasant = as.numeric(pleasant),
    participant_id = as.numeric(participant_id),
    session_id = as.numeric(session_id)
  ) %>%
mutate(
  across(c(init_time, completion_time), 
         ~ lubridate::with_tz(
             as.POSIXct(., 
                        format = "%Y-%m-%d %H:%M:%OS",
                        tz = "America/New_York"),
             tzone = "UTC"
           ))
)

# Quick glimpse
glimpse(part2beeped)


```


#Run the 'clean_names' function in the janitor package, so that variable names with hyphens become variable names with underscores and all text in variable names becomes lowercase (e.g., 'Milestone_1' -> 'milestone_1').
```{r}
part2beeped <- clean_names(part2beeped)
```

# Save processed data to the /output directory
```{r}
saveRDS(part2beeped, here("output", "part2beeped.rds"))
```

